name: Update Metrics
on:
  schedule: [{cron: "30 4 * * 1,4"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Carter4242
          template: classic
          base: header, activity, metadata
          base_indepth: yes
          config_timezone: America/New_York
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          plugin_activity_limit: 4
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, push
